version: '3'

services:
    webapp:
        container_name: webapp
        build: 
          context: ./app
        ports:
            - "80:5000"
        depends_on:
            - mongodb
    mongodb:
        container_name: mongodb
        build:
          context: ./mongodb
        ports:
            - "27017:27017"
        volumes:
          - ./mongodb/db:/data/db

volumes:
    local_mongo_db:
        